on:
  workflow_dispatch:

jobs:
  job-runner:
    strategy:
      matrix:
        job: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bash api-call.sh
        env:
          REPO: ${{ github.repository }}
